# Habilita o suporte geral a displays
CONFIG_ZMK_DISPLAY=y

# Habilita o barramento I2C (Essencial para o Lily58)
CONFIG_I2C=y

# Driver específico para a tela OLED SSD1306
CONFIG_SSD1306=y

# Configurações de Widgets (O que aparece na tela)
CONFIG_ZMK_WIDGET_LAYER_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y
CONFIG_ZMK_WIDGET_WPM_STATUS=y

# Melhora a estabilidade de boot do display
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y
