# --- DISPLAY SETTINGS ---
# Habilita o suporte ao display OLED
CONFIG_ZMK_DISPLAY=y
# Melhora a compatibilidade do driver SSD1306
CONFIG_I2C=y
CONFIG_SSD1306=y

# Widgets de status (Bateria, Camada, Saída)
CONFIG_ZMK_WIDGET_LAYER_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y
CONFIG_ZMK_WIDGET_WPM_STATUS=y

# --- POWER MANAGEMENT ---
# Habilita o modo de suspensão profunda (Deep Sleep)
CONFIG_ZMK_SLEEP=y
# Entra em Deep Sleep após 15 minutos (15 * 60 * 1000ms)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# --- BLUETOOTH SETTINGS ---
# Aumenta a potência do rádio para evitar interferências
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
# Melhora a estabilidade da conexão com Windows/Ryzen
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
