# Habilita o display OLED
CONFIG_ZMK_DISPLAY=y

# Opcional: Melhora a estabilidade em alguns controladores nRF
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y

# Se você estiver usando o widget padrão do ZMK
CONFIG_ZMK_WIDGET_LAYER_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y
